services:
  VPA:
    image: mwdle/vpa:latest
    container_name: VPA
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - VPA
    volumes:
      - ${DOCKER_VOLUMES}/VPA/VirtualPublicArtboard:/VPA
    environment:
      - NODE_ENV=production
      - APP_TITLE=Virtual Public Artboard
      - FILE_NUM_LIMIT=50
    deploy:
      resources:
        limits: 
          cpus: '0.15'
          memory: 20M

networks:
  VPA:
    name: VPA
    external: true